[package]
name = "sql2godb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^4.5.4", features = ["derive"] }
clap_derive = { version = "4.0.0-rc.1" }
convert_case = "0.6.0"
